
name: master_record_app
description: Master Record - standalone Master Person Identity System client app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # State management
  flutter_riverpod: ^2.5.1

  # Networking
  dio: ^5.4.3+1
  http_parser: ^4.0.0

  # Image / file picking
  image_picker: ^1.1.2
  file_picker: ^12.1.2

  # Date formatting
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

